### ISSUE TITLE
[PERTANYAAN] Apakah tujuan organisasi ini?

### ISSUE THREAD

**Issue by eraraya-ricardo** [Indonesia-Menjadi-Lebih-Baik/Penjelasan-Saran-dan-Kritik#1]
Saya senang melihat ada inisiatif seperti ini. Tetapi alangkah baiknya kalau ada penjelasan yg jelas tentang apa latar belakang dan tujuan organisasi ini, kemudian siapa saja orang dibelakangnya, seperti apa project yg akan dilakukan, dsb.
Jika pertanyaan-pertanyaan tersebut bisa dijelaskan dengan meyakinkan, saya tentu dengan senang hati akan membantu.

Salam.

**Comment by CreepyMRED** [comment]
Terima kasih sarannya @eraraya-ricardo 

Maafkan saya untuk mengundang orang-orang tanpa memberitahu dan menjelaskan terlebih dahulu tujuan dan latar belakang dari organisasi ini. Saya akan menambahkan tujuan dan latar belakan organisasi ini di repositori secepatnya. Sementara, saya akan menjelaskan tujuan dan latar belakang secara singkat tentang organisasi serta visi dan misinya.

Organisasi ini memiliki nama sementara Indonesia Menjadi Lebih Baik, organisasi ini lebih mirip dengan ormas-ormas yang terdapat di masyarakat.

Organisasi ini (seperti yang ada di deskripsi) bertujuan menciptakan ekosistem teknologi yang bertujuan menyelesaikan isu-isu yang ada di negara kita (selengkapnya nanti). Diharapkan ekosistem ini dapat menggantikan ekosistem perusahaan-perusahaan dari luar yang tidak membantu negara kita untuk menjadi maju.

Beberapa isu yang bisa saya uraikan sekarang antara lain,
- Polarisasi digital
- Nasionalisme para kaum muda
- Kemajuan Indonesia dalam Informasi dan Teknologi
- Dan isu terkait lainnya

Sementara ini belum ada instansi atau orang yang membelakangi organisasi ini, masih saya seorang.

Diharapkan dengan mengundang orang-orang untuk bergabung, setidaknya terdapat satu dua orang yang berkenan.

Sekian, terimakasih

Salam baik.

**Comment by eraraya-ricardo** [comment]
Terima kasih atas jawabannya. Bolehkah saya tahu nama dan latar belakang mas?

**Comment by CreepyMRED** [comment]
Nama saya tertera di lama profil saya. Untuk latar belakang belum bisa saya umbar untuk sekarang demi kelancaran proyek ini. Dimohon untuk pemahamannya. Organisasi ini benar-benar mencari sukarelawan, diharapkan tidak berharap besar terhadap imbal balik dari usaha di dalam organisasi ini.
Terimakasih

**Comment by eraraya-ricardo** [comment]
Yg namanya project open-source tentu tidak berbayar. Saya tidak bertanya karena berharap imbal balik dan bayaran. Saya hanya merasa kalau orang2 yang nantinya mungkin membantu (termasuk saya) berhak untuk tau latar belakang dan profil dari maintainer repository ini. Kalau profil pemiliknya tidak tertera dengan jelas, saya sendiri agak ragu untuk berkontribusi karena tidak tahu akan digunakan untuk apa repositorynya nanti dan tidak tahu harus menuntut pertanggung jawaban pada siapa jika disalah gunakan.

Untuk saat ini saya paham jika belum sempat memperkenalkan diri karena masih proses pembentukan dan pastinya mas perlu mengurusi banyak hal lainnya. Tetapi jika semua persiapan sudah matang, alangkah baiknya jika dilakukan sebuah perkenalan formal tentang profil mas. Saya rasa ini etika yang baik juga dalam bekerjasama. Terima kasih mas.

Sekian dan salam.

**Comment by creepymred** [comment]
Maaf sebelumnya jika komentar saya menyinggung. Saat ini saya sedang melakukan perencanaan dan pembuatan fondasi untuk proyek-proyek yang ada di dalam organisasi ini. Setelah membaca komentar dari saudara @eraraya-ricardo, saya jadi ingin mengubah rencana awal saya. Awalnya saya ingin memperkenalkan diri setelah saya mem _pull_ hasil kerja saya nanti yang berkaitan dengan proyek-proyek di organisasi ini. Baiklah oleh karena itu saya akan memperkenalkan diri secara singkat di komentar ini (nantinya saya tambahkan ke profil saya). 

> Tak kenal maka tak sayang

Nama : M. Refi Dwi Ananta
Status : Pelajar SMA Kelas XII (segera lulus Insha Allah)
Pengalaman dalam bidang teknologi informasi : 

1. Mempelajari dunia pemrograman selama ±7 tahun.
2. Diawali dengan mempelajari JavaScript, Java, Python, dan R.
3. Sekarang memeluk bahasa Rust
4. Belum ada pengalaman profesional
5. Membuat website dengan Django
6. Linux from scratch (jika dihitung)
7. Sekarang sedang membuat implementasi Cardano dan Nano dalam bahasa Rust

Dikarenakan latar belakang tersebutlah saya menjadi ragu untuk memperkenalkan diri sekarang. Dikarenakan waktu kosong yang saya miliki sekarang hingga masuk ke dunia perkuliahan nanti, saya memiliki ide untuk membuat organisasi ini. Ide ini diawali dari pengamatan saya terhadap perilaku generasi saya dan keadaan Indonesia dalam bidang teknologi sekarang yang menurut saya tidak membaik. Diharapkan dengan dimulainya organisasi ini saya dapat memberi pengaruh yang cukup besar bagi negeri ini.
